---
- name: Make sure all packages used by .i3config are installed
  apt:
    pkg:
      - i3blocks
      - rxvt-unicode
      - xautolock
      - feh # wallpaper
      - gnome-screensaver
      - udevil # automount
      - pulseaudio-module-bluetooth # allows sending audio to bluetooth devices
    state: installed
    update_cache: yes
  become: yes

- name: Install i3 - add apt repo
  apt_repository: repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe' state=present
  become: yes

- name: Install i3
  apt:
    name: i3
    update_cache: yes
    force: yes
  become: yes

- name: Setup lightdm
  copy:
    src: "lightdm/"
    dest: "/etc/lightdm/lightdm.conf.d/"
    mode: 0755
  become: yes

- name: Link .i3 dir from the dotfiles repo
  file:
    src: "{{ user_home_dir }}/.dotfiles/.i3"
    dest: "{{ user_home_dir }}/.i3"
    state: link
  become: yes
  become_user: "{{ machine_user }}"

- name: Link .i3blocks.conf from the dotfiles repo
  file:
    src: "{{ user_home_dir }}/.dotfiles/.i3blocks.conf"
    dest: "{{ user_home_dir }}/.i3blocks.conf"
    state: link
  become: yes
  become_user: "{{ machine_user }}"

- name: Link .Xdefaults from the dotfiles repo
  file:
    src: "{{ user_home_dir }}/.dotfiles/.Xdefaults"
    dest: "{{ user_home_dir }}/.Xdefaults"
    state: link
  become: yes
  become_user: "{{ machine_user }}"

- name: Install font-awesome (displaying nice icons in i3blocks)
  apt:
    name: fonts-font-awesome
    update_cache: yes
    force: yes
  become: yes
